### ISSUE TITLE
Qt UI is missing `about` button

### ISSUE THREAD

**Issue by yorickvP** [serokell/ariadne#179]
also any splash text

**Comment by gromakovsky** [comment]
We are disabling GitHub issues in favor of YouTrack (https://github.com/serokell/ariadne/tree/1574990946d8b8d3cef0c6df2f6a767c89856b0d#issue-tracker).
In [AD-375](https://issues.serokell.io/issue/AD-375) we are going to add a dialog with `About` button which will show some information.
There is an open PR for that https://github.com/serokell/ariadne/pull/329.
