### ISSUE TITLE
[AD-64] Hide sensitive data

### ISSUE THREAD

**Issue by sectore** [serokell/ariadne#182]
Just watched the [screencast](https://www.youtube.com/watch?v=fZClnx1WkrU) ^ - great stuff! 

It would be nice to display PW as `*****` - But I guess you have already that on your radar.

![screenshot](https://user-images.githubusercontent.com/47693/41189485-f6c561d6-6bce-11e8-87ee-5bbb8d84ded4.png)

**Comment by yegortimoshenko** [comment]
Actually, we didn't have that on radar, until now :-) Thanks for bringing it up!

**Comment by pasqu4le** [comment]
solved with #310
