### ISSUE TITLE
stack build ariadne fails on Arch Linux

### ISSUE THREAD

**Issue by archfan** [serokell/ariadne#184]
Here's what I get:

`    src/tcmalloc.cc:332] Attempt to free invalid pointer 0x16f94c0
--  While building custom Setup.hs for package cardano-sl-lrc-1.2.0 using:
      /home/y/.stack/setup-exe-cache/x86_64-linux-tinfo6/Cabal-simple_mPHDZzAJ_1.24.2.0_ghc-8.0.2 --builddir=.stack-work/dist/x86_64-linux-tinfo6/Cabal-1.24.2.0 build lib:cardano-sl-lrc --ghc-options " -ddump-hi -ddump-to-file"`

`    Process exited with code: ExitFailure (-6)
    Logs have been written to: /home/y/ariadne/.stack-work/logs/cardano-sl-lrc-1.2.0.log
    Configuring cardano-sl-lrc-1.2.0...
    Preprocessing library cardano-sl-lrc-1.2.0...
    [ 1 of 13] Compiling Pos.Lrc.Types    ( Pos/Lrc/Types.hs, .stack-work/dist/x86_64-linux-tinfo6/Cabal-1.24.2.0/build/Pos/Lrc/Types.o )
    [ 2 of 13] Compiling Pos.Lrc.RichmenComponent ( Pos/Lrc/RichmenComponent.hs, .stack-work/dist/x86_64-linux-tinfo6/Cabal-1.24.2.0/build/Pos/Lrc/RichmenComponent.o )
    [ 3 of 13] Compiling Pos.Lrc.Fts      ( Pos/Lrc/Fts.hs, .stack-work/dist/x86_64-linux-tinfo6/Cabal-1.24.2.0/build/Pos/Lrc/Fts.o )
    src/tcmalloc.cc:332] Attempt to free invalid pointer 0x1465900
`

**Comment by Pastafarianist** [comment]
Try `sudo pacman -S jemalloc`. This will force RocksDB to be built with `jemalloc` instead of `tcmalloc`.

**Comment by archfan** [comment]
I've installed jemalloc and rebuilt rocksdb using jemalloc. I'm still getting a similar error during the build process:

`cardano-sl-networking-1.2.0: copy/register                                                  
cardano-sl-util-1.2.0: configure (lib)                                                      
cardano-sl-util-1.2.0: build (lib)                                                          
dhall-1.7.0: copy/register                                                            
cardano-sl-util-1.2.0: copy/register                                                  
cardano-sl-crypto-1.2.0: configure (lib)                                 
cardano-sl-crypto-1.2.0: build (lib)                                       
swagger2-2.1.4.1: copy/register                                            
servant-swagger-1.1.4: configure                                                
servant-swagger-1.1.4: build                                                    
cardano-sl-crypto-1.2.0: copy/register                                          
cardano-sl-core-1.2.0: configure (lib)                                          
cardano-sl-core-1.2.0: build (lib)                                              
servant-swagger-1.1.4: copy/register                                          
qtah-cpp-0.5.0: copy/register                                                 
qtah-0.5.0: configure (lib)                            
qtah-0.5.0: build (lib)                                
cardano-sl-core-1.2.0: copy/register               
cardano-sl-db-1.2.0: configure (lib)               
cardano-sl-db-1.2.0: build (lib)                   
qtah-0.5.0: copy/register                        
Progress 195/207            

--  While building custom Setup.hs for package cardano-sl-db-1.2.0 using:
      /home/y/.stack/setup-exe-cache/x86_64-linux-tinfo6/Cabal-simple_mPHDZzAJ_1.24.2.0_ghc-8.0.2 --builddir=.stack-work/dist/x86_64-linux-tinfo6/Cabal-1.24.2.0 build lib:cardano-sl-db --ghc-options " -ddump-hi -ddump-to-file"
    Process exited with code: ExitFailure 1
    Logs have been written to: /home/y/ariadne/.stack-work/logs/cardano-sl-db-1.2.0.log

    Configuring cardano-sl-db-1.2.0...
    Preprocessing library cardano-sl-db-1.2.0...
    [ 1 of 14] Compiling Pos.DB.Error     ( Pos/DB/Error.hs, .stack-work/dist/x86_64-linux-tinfo6/Cabal-1.24.2.0/build/Pos/DB/Error.o )
    [ 2 of 14] Compiling Pos.DB.Class     ( Pos/DB/Class.hs, .stack-work/dist/x86_64-linux-tinfo6/Cabal-1.24.2.0/build/Pos/DB/Class.o )
    [ 3 of 14] Compiling Pos.DB.Functions ( Pos/DB/Functions.hs, .stack-work/dist/x86_64-linux-tinfo6/Cabal-1.24.2.0/build/Pos/DB/Functions.o )
    [ 4 of 14] Compiling Pos.DB.Misc.Common ( Pos/DB/Misc/Common.hs, .stack-work/dist/x86_64-linux-tinfo6/Cabal-1.24.2.0/build/Pos/DB/Misc/Common.o )
    [ 5 of 14] Compiling Pos.DB.Pure      ( Pos/DB/Pure.hs, .stack-work/dist/x86_64-linux-tinfo6/Cabal-1.24.2.0/build/Pos/DB/Pure.o )
    <command line>: can't load .so/.DLL for: /home/y/ariadne/.stack-work/install/x86_64-linux-tinfo6/lts-9.1/8.0.2/lib/x86_64-linux-ghc-8.0.2/libHSrocksdb-haskell-ng-0.0.0-BPSkHsduThH6PzJe4xDk0s-ghc8.0.2.so (/usr/lib/libjemalloc.so.2: cannot allocate memory in static TLS block)
`

**Comment by Pastafarianist** [comment]
This is a different error. It arises intermittently, but always while building the DB bindings and only with `jemalloc` version 5. Downgrading to `4.5.0-1` solves the issue, but with some configurations `5.1.0-1` seems to work OK too (I have `extra/jemalloc 1:5.1.0-1 [installed]`). We haven't looked into why RocksDB bindings behave like that. For an easy solution, try downgrading to `4.5.0-1`.

**Comment by archfan** [comment]
Thanks! Downgrading to 4.5.0 did the trick. 

I really like this wallet so far.

**Comment by Pastafarianist** [comment]
Glad to help!
