### ISSUE TITLE
Illegal instruction (core dumped) on launch

### ISSUE THREAD

**Issue by Xa52c** [serokell/ariadne#188]
Receive this error immediately upon launch

**Comment by maksbotan** [comment]
Can you please specify you OS (macOS or a specific Linux distro) and your CPU?

Also, it would be great if you tried running ariadne with a debugger. To do so, run `gdb --args sh ./ariadne-bundle-linux`, then type `r` in gdb prompt and wait untill you get `illegal instruction`.

After that please type `bt` to get a stack trace and paste it here. You can also type `layout asm` to switch to assembly view and show us which specific instruction failed: https://stackoverflow.com/a/2015523.

**Comment by Xa52c** [comment]
Ubuntu 18.04 LTS
PENTIUM dual core E5200 @ 2.5GHZ X 2
Memory 3.9 Gb

Interior 1 (process 2825) exited with code 0204

No stack.

**Comment by yegortimoshenko** [comment]
Sorry, that's too old. We can't support that without major performance hit, at least not in our build.

**Comment by maksbotan** [comment]
You are still welcome to build ariadne using instructions in README.md and tell us if it works for you :)
It should not be hard, but may take some time.
